import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  loadingState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: '#ffffff',
  },
  container: {
    paddingBottom: 32,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f4f4f4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 12,
  },
  errorBanner: {
    marginBottom: 16,
    borderRadius: 12,
    backgroundColor: '#fff5f5',
    borderWidth: 1,
    borderColor: '#f5c2c2',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  errorBannerText: {
    color: '#c53030',
    fontSize: 14,
  },
  imagePreview: {
    height: 220,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e5e5e5',
    backgroundColor: '#fafafa',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  heroPlaceholderText: {
    color: '#6c6c6c',
    fontSize: 14,
    marginTop: 12,
  },
  paginationDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginVertical: 16,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#dcdcdc',
  },
  activeDot: {
    backgroundColor: '#111111',
    width: 18,
  },
  productInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  productName: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111111',
  },
  productMeta: {
    color: '#6c6c6c',
    marginTop: 4,
  },
  productDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: '#4a4a4a',
    marginBottom: 16,
  },
  pricingCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ececec',
    backgroundColor: '#ffffff',
    padding: 16,
    marginBottom: 24,
    gap: 12,
  },
  pricingTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111111',
  },
  pricingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pricingLabel: {
    fontSize: 14,
    color: '#6c6c6c',
  },
  pricingValue: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111111',
  },
  quickActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  quickAction: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  quickActionActive: {
    borderBottomWidth: 2,
    borderBottomColor: '#111111',
    paddingBottom: 8,
  },
  quickActionLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: '#6f6f6f',
  },
  quickActionLabelActive: {
    color: '#111111',
  },
  primaryButton: {
    backgroundColor: '#000000',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 24,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 24,
  },
  secondaryButtonText: {
    color: '#111111',
    fontSize: 16,
    fontWeight: '600',
  },
  cardSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111111',
    marginBottom: 16,
  },
  relatedRow: {
    flexDirection: 'row',
    gap: 16,
  },
  relatedCard: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e1e1e1',
    padding: 16,
    backgroundColor: '#ffffff',
  },
  relatedBadge: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
    backgroundColor: '#000000',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 12,
  },
  relatedSubtitle: {
    fontSize: 14,
    color: '#444444',
    marginBottom: 12,
  },
  relatedPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111111',
  },
  reviewCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e1e1e1',
    padding: 16,
    backgroundColor: '#ffffff',
  },
  reviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    alignItems: 'center',
  },
  reviewName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111111',
  },
  ratingRow: {
    flexDirection: 'row',
    gap: 4,
  },
  reviewComment: {
    color: '#444444',
    fontSize: 14,
    lineHeight: 20,
  },
  reviewSeparator: {
    height: 12,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modalContent: {
    width: '100%',
    borderRadius: 16,
    backgroundColor: '#ffffff',
    padding: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111111',
    marginBottom: 16,
  },
  modalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  modalLabel: {
    fontWeight: '500',
    color: '#333333',
  },
  modalValue: {
    color: '#666666',
  },
  modalEmptyState: {
    paddingVertical: 4,
  },
  modalEmptyText: {
    fontSize: 14,
    color: '#6f6f6f',
    textAlign: 'center',
  },
  modalCloseButton: {
    marginTop: 12,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: '#000000',
    alignItems: 'center',
  },
  modalCloseText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  authModalContent: {
    width: '100%',
    borderRadius: 16,
    backgroundColor: '#ffffff',
    padding: 24,
  },
  authModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111111',
    marginBottom: 12,
  },
  authModalDescription: {
    fontSize: 14,
    color: '#444444',
    marginBottom: 20,
    lineHeight: 20,
  },
  authModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  authModalSecondary: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d9d9d9',
    backgroundColor: '#ffffff',
  },
  authModalSecondaryText: {
    color: '#444444',
    fontWeight: '600',
  },
  authModalPrimary: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: '#111111',
  },
  authModalPrimaryText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  authModalLink: {
    marginTop: 16,
    alignItems: 'center',
  },
  authModalLinkText: {
    color: '#111111',
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  rentModalContent: {
    width: '100%',
    borderRadius: 20,
    backgroundColor: '#ffffff',
    padding: 24,
  },
  rentModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  rentModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111111',
  },
  rentModalClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f4f4f4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rentSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  rentSummaryThumb: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: '#f4f4f4',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  rentSummaryDetails: {
    flex: 1,
  },
  rentSummaryName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111111',
  },
  rentSummaryMeta: {
    color: '#6f6f6f',
    marginTop: 4,
  },
  rentSummaryPrice: {
    color: '#111111',
    fontWeight: '600',
    marginTop: 4,
  },
  rentFieldGroup: {
    marginBottom: 18,
  },
  rentFieldLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111111',
    marginBottom: 8,
  },
  rentInfoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: '#eef4ff',
    borderWidth: 1,
    borderColor: '#d2e3ff',
    marginBottom: 18,
  },
  rentInfoText: {
    flex: 1,
    color: '#1a73e8',
    fontSize: 14,
    lineHeight: 20,
  },
  rentTotalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: '#f7f7f7',
    borderWidth: 1,
    borderColor: '#ededed',
    marginBottom: 18,
  },
  rentTotalLabel: {
    fontSize: 14,
    color: '#6f6f6f',
  },
  rentTotalValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111111',
  },
  rentQuantityControl: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fafafa',
  },
  rentQuantityButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e1e1e1',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rentQuantityButtonDisabled: {
    opacity: 0.5,
  },
  rentQuantityValue: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111111',
  },
  rentStockLabel: {
    marginTop: 8,
    color: '#6f6f6f',
  },
  rentFooter: {
    marginTop: 8,
    alignItems: 'stretch',
  },
  rentPrimaryAction: {
    borderRadius: 12,
    backgroundColor: '#111111',
    paddingVertical: 16,
    alignItems: 'center',
    width: '100%',
  },
  rentPrimaryActionText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  cartModeButton: {
    backgroundColor: '#f4f4f4',
    borderWidth: 1,
    borderColor: '#111111',
  },
  cartModeButtonText: {
    color: '#111111',
  },
  disabledButton: {
    opacity: 0.5,
  },
  disabledButtonText: {
    color: '#cccccc',
  },
});

export default styles;
